# Generated by Django 3.2 on 2021-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictPandemiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': [('is_admin', 'is admin')]},
        ),
        migrations.AlterModelOptions(
            name='custom',
            options={'permissions': [('is_custom', 'is custom')]},
        ),
    ]
