# Generated by Django 3.2 on 2021-06-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictPandemiApp', '0002_auto_20210505_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
